### ISSUE TITLE
Upgrade beberlei/assert to ^3.x

### ISSUE THREAD

**Issue by erickjth** [lezhnev74/ddd-generator#1]
Hey, thanks for this nice tool.

I would like to know if you have a plan to upgrade some dependencies like beberlei/assert to use the more recent version?

Currently, it is generating conflicts in the composer installation.

👍

**Comment by lezhnev74** [comment]
Hey! I've just tagged an update! 
Does it solve your conflicts?

**Comment by erickjth** [comment]
Did you publish that version in packagist.org?

**Comment by lezhnev74** [comment]
Yeah, the way Packagist integrates with Github has been changed.
